### ISSUE TITLE
Styling Issues

### ISSUE THREAD

**Issue by alexanderbock** [SciVis/Orfan#4]
- [x] Showing tags on the left side to be close to the breadcrumb elements
- [x] Click on element bar to expand instead of just the (...) element
- [x] Add a slider to change the size of objects in the main grid to show more or less information for each element
  - Smaller value -> smaller images, less text
  - Bigger value -> more text
- [x] Remove the empty citations list if there are no citations
- [x] Remove the empty files list if there are no citations

**Comment by scanberg** [comment]
I think I understand all of your points here, but the one that will probably not be so trivial is the Slider to change the size. Depending on what you mean.

Currently there are two views for each item, the 'thumbnail' (minimized) and maximized views which are both static in their designs, so the information that is displayed in each is static. (Even though the text in minimized view gets clipped with ...)

One could however change the size of the container of the items through a slider and thus the image would become bigger and more text would be visible.

Is that what you meant or could you elaborate more on your ideas regarding the slider?

**Comment by alexanderbock** [comment]
Right now on full-screen, I can see 4 columns and 2 rows of containers at the same time..  Basically, the slider idea is that the containers are shrinked (similar to when you make the browser really small horizontally). The dot on the 1 would be if the amount of data that is shown also depends on the slider values (slider low: show a grid of many more items at the same time, but maybe only the name and tags; slider a bit higher: show the name, tags and a small image; slider higher: start showing the directories and the text underneath; slider at maximum: basically like it is now

**Comment by petersteneteg** [comment]
I think that is quite lot of work for a nice but maybe not really need feature at this point...

**Comment by scanberg** [comment]
Added XL column node, which will provide yet another scaling for displays larger than 1600px. This is a more or less temporary fix to the scaling issues. If we still think a slider is needed then I'll look further into that.
